"""add media assets table

Revision ID: 240dfefa52bd
Revises: 
Create Date: 2026-01-30 11:14:17.184780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240dfefa52bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('drive_file_id', sa.String(length=255), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('thumbnail_url', sa.Text(), nullable=True),
        sa.Column('play_url', sa.Text(), nullable=True),
        sa.Column('project_name', sa.String(length=100), nullable=True),
        sa.Column('shoot_date', sa.Date(), nullable=True),
        sa.Column('shoot_day', sa.Integer(), nullable=True),
        sa.Column('crew_member_id', sa.String(length=20), nullable=True),
        sa.Column('status', sa.Enum('RAW', 'REVIEWED', 'APPROVED'), nullable=True),
        sa.Column('assigned_reviewer_id', sa.String(length=20), nullable=True),
        sa.Column('meta_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['crew_member_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('drive_file_id')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_project_name'), ['project_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_project_name'))

    op.drop_table('media_assets')
    # ### end Alembic commands ###
